pyuic6 client/buttonbox_client/ui/about.ui -o client/buttonbox_client/ui/about_ui.py
pyuic6 client/buttonbox_client/ui/custom_actions.ui -o client/buttonbox_client/ui/custom_actions_ui.py
pyuic6 client/buttonbox_client/ui/edit_macro_action.ui -o client/buttonbox_client/ui/edit_macro_action_ui.py
pyuic6 client/buttonbox_client/ui/keyboard.ui -o client/buttonbox_client/ui/keyboard_ui.py
pyuic6 client/buttonbox_client/ui/licenses.ui -o client/buttonbox_client/ui/licenses_ui.py
pyuic6 client/buttonbox_client/ui/macro_editor.ui -o client/buttonbox_client/ui/macro_editor_ui.py
pyuic6 client/buttonbox_client/ui/profile_editor.ui -o client/buttonbox_client/ui/profile_editor_ui.py
pyuic6 client/buttonbox_client/ui/profiles.ui -o client/buttonbox_client/ui/profiles_ui.py
pyuic6 client/buttonbox_client/ui/serial_monitor.ui -o client/buttonbox_client/ui/serial_monitor_ui.py
pyuic6 client/buttonbox_client/ui/settings.ui -o client/buttonbox_client/ui/settings_ui.py
pyuic6 client/buttonbox_client/ui/window.ui -o client/buttonbox_client/ui/window_ui.py
